sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.4.2"
  - "3.4.7"
  - "4.0.0-preview.5"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix js